src/Entity/Glossaire.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GlossaireRepository")
 */
class Glossaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_latin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNomLatin(): ?string
    {
        return $this->nom_latin;
    }

    public function setNomLatin(string $nom_latin): self
    {
        $this->nom_latin = $nom_latin;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/GlossaireType.php
<?php

namespace App\Form;

use App\Entity\Glossaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GlossaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('nom_latin')
            ->add('image', FileType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Glossaire::class,
        ]);
    }
}

src/Controller/GlossaireController.php
<?php

namespace App\Controller;

use App\Entity\Glossaire;
use App\Form\GlossaireType;
use App\Repository\GlossaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/glossaire")
 */
class GlossaireController extends AbstractController
{
    /**
     * @Route("/", name="glossaire_index", methods={"GET"})
     */
    public function index(GlossaireRepository $glossaireRepository): Response
    {
        return $this->render('glossaire/index.html.twig', [
            'glossaires' => $glossaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="glossaire_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $glossaire = new Glossaire();
        $form = $this->createForm(GlossaireType::class, $glossaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($glossaire);
            $entityManager->flush();

            return $this->redirectToRoute('glossaire_index');
        }

        return $this->render('glossaire/new.html.twig', [
            'glossaire' => $glossaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="glossaire_show", methods={"GET"})
     */
    public function show(Glossaire $glossaire): Response
    {
        return $this->render('glossaire/show.html.twig', [
            'glossaire' => $glossaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="glossaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Glossaire $glossaire): Response
    {
        $form = $this->createForm(GlossaireType::class, $glossaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('glossaire_index');
        }

        return $this->render('glossaire/edit.html.twig', [
            'glossaire' => $glossaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="glossaire_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Glossaire $glossaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$glossaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($glossaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('glossaire_index');
    }
}

templates/glossaire/_delete_form.html.twig
<form method="post" action="{{ path('glossaire_delete', {'id': glossaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ glossaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/glossaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/glossaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Glossaire{% endblock %}

{% block body %}
    <h1>Edit Glossaire</h1>

    {{ include('glossaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('glossaire_index') }}">back to list</a>

    {{ include('glossaire/_delete_form.html.twig') }}
{% endblock %}

templates/glossaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Glossaire index{% endblock %}

{% block body %}
    <h1>Glossaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Nom_latin</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for glossaire in glossaires %}
            <tr>
                <td>{{ glossaire.id }}</td>
                <td>{{ glossaire.nom }}</td>
                <td>{{ glossaire.description }}</td>
                <td>{{ glossaire.nomLatin }}</td>
                <td>{{ glossaire.image }}</td>
                <td>
                    <a href="{{ path('glossaire_show', {'id': glossaire.id}) }}">show</a>
                    <a href="{{ path('glossaire_edit', {'id': glossaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('glossaire_new') }}">Create new</a>
{% endblock %}

templates/glossaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Glossaire{% endblock %}

{% block body %}
    <h1>Create new Glossaire</h1>

    {{ include('glossaire/_form.html.twig') }}

    <a href="{{ path('glossaire_index') }}">back to list</a>
{% endblock %}

templates/glossaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Glossaire{% endblock %}

{% block body %}
    <h1>Glossaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ glossaire.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ glossaire.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ glossaire.description }}</td>
            </tr>
            <tr>
                <th>Nom_latin</th>
                <td>{{ glossaire.nomLatin }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ glossaire.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('glossaire_index') }}">back to list</a>

    <a href="{{ path('glossaire_edit', {'id': glossaire.id}) }}">edit</a>

    {{ include('glossaire/_delete_form.html.twig') }}
{% endblock %}